from docx import Document
from docx.shared import Inches, Pt
from docx.oxml.ns import qn
from pathlib import Path
import re

root = Path(__file__).resolve().parents[1]
source = root / "gTheoryShiny_EPM_manuscript.docx"
doc = Document(source)

sections = {
"Application Distinctiveness": [
"gTheoryShiny is designed around the observation that an applied G-theory analysis is a sequence of linked decisions. The software therefore treats data shape, design structure, model specification, estimation, D-study projection, and reporting as one workflow. This is different from presenting a coefficient calculator beside a data table. The user is asked to inspect the raw table, make facet labels explicit, confirm the unit and outcome, review the inferred relationship table, and read the recommended formula before fitting the model. Each step creates an object that can be inspected or downloaded. This design makes errors easier to locate because a problem in a final coefficient can be traced to a specific earlier representation or assumption.",
"The first distinctive feature is reversible data preparation. The application supports long-format records and wide-format assessment files with header rows that encode facets. A transformation is not accepted merely because it produces rows; the application checks that facet prefixes and names are supplied consistently, that transformed observations exist, and that a changed source file invalidates an earlier transformed object. This protects against a particularly dangerous class of error: the interface appears to respond normally while the fitted model still represents a previous file. The raw and transformed tables remain available so that an analyst can show a collaborator exactly how the design was encoded.",
"The second distinctive feature is design visibility. Many statistical interfaces expose variable selectors but do not show how observed combinations imply crossed, nested, or confounded relationships. gTheoryShiny displays a pairwise structure table and reports when a one-to-one pattern makes two selected facets empirically inseparable. This does not replace substantive design documentation, but it gives the analyst a concrete diagnostic before model fitting. The same structure is carried into formula construction, so the displayed model is connected to the relationship table rather than selected from an unexplained menu.",
"The third feature is state-preserving bilingual interaction. English and Simplified Chinese are implemented through stable internal keys and translated visible labels. Changing language updates labels, placeholders, switches, table headings, interpretations, and option text without changing the underlying values such as identity, omit, or a selected facet name. The distinction is important in collaborative work: a researcher can inspect an analysis in Chinese, switch to English for a manuscript meeting, and return to Chinese without refitting or losing a D-study scenario. Browser tests exercise this behavior after G- and D-study results have been produced.",
"The fourth feature is explicit safety and diagnostics. Custom formulas are restricted to a small declarative syntax, and executable expressions are rejected. Unknown variables, empty terms, duplicated roles, nonnumeric outcomes, incompatible link functions, sparse facets, and nonreplicated random terms produce user-facing validation messages. Model singularity and convergence warnings are reported in the results panel. These safeguards do not guarantee a correct model; they make common failures visible and reduce the chance that a warning is silently ignored.",
"The fifth feature is a separation between analysis and explanation. The statistical path computes model results; the interpretation panel translates coefficients and warnings into plain language; the optional AI Assistant receives aggregate context only. This architecture prevents the language layer from becoming a second estimator. It also allows the user to download numerical tables while treating explanatory text as a convenience that should be checked against the design and the displayed model."
],
"Full Walkthrough of Advanced Functions": [
"A complete analysis begins by selecting a dataset. The bundled Brennan.3.2 example is useful for a two-facet crossed workflow, whereas Rajaratnam.2 is useful for showing a different facet configuration. To upload a file, the user switches from Example data to Uploaded data, selects a CSV, and chooses whether a header is present. The raw table should be inspected for identifier columns, outcome columns, missing values, and facet labels. A file that looks plausible can still encode the wrong design, so this inspection is part of the analysis rather than a preliminary chore.",
"For wide data, the user turns off Long format. The application then requests the number of rows containing facet labels, prefixes for those labels, and names for the resulting facets. For example, two label rows containing Task and Rater can be represented with prefixes T and R and names Task and Rater. The transformed output should contain one Person, Task, Rater, and Score record per response. If the prefixes do not match the data, the application stops with a validation message instead of generating a partially labeled table. The user can download the transformed file and ask a second analyst to review it before continuing.",
"In Data Structure, the user chooses the measurement object, outcome, and one or more facets. The ID should identify the unit whose score interpretation matters; it should not be a row number or an accidental combination of variables. The outcome should be numeric or safely convertible to numeric. Facets should represent sampled or modeled conditions such as items, raters, tasks, occasions, or stations. Covariates may be selected as fixed effects, but the user should explain why they belong in the score model and should report whether their inclusion changes the variance components.",
"The missing-data control has four choices. Omission is the default and is transparent when the estimand is based on complete selected variables. Zero replacement is appropriate only when zero is substantively a valid response, not merely a convenient code. Mean and median replacement are available for sensitivity demonstrations, but they can reduce observed variance and change the estimated error structure. The walkthrough therefore recommends running a sensitivity comparison and recording the choice in the study log. The application reports how many rows remain after the selected operation and stops if no usable observations remain.",
"The structure table should be read before accepting the recommended formula. A crossed pair contributes main facet terms and an interaction term; a nested pair contributes the appropriate parent and nested interaction terms; and a confounded pair triggers a warning because separate effects cannot be identified from the selected combinations. The user should compare the table with the assessment blueprint. If the blueprint says that raters are crossed with tasks but the table shows nesting, the discrepancy may reflect a data-collection restriction, a coding error, or a different intended universe.",
"The link-function control makes the family assumption explicit. Identity is the natural starting point for approximately continuous scores. Logit requires outcomes coded 0 and 1; Poisson requires nonnegative integer counts; and inverse gamma requires strictly positive outcomes. The checks prevent an obviously incompatible model, but they do not establish distributional adequacy. Analysts should examine score distributions and residual diagnostics and should explain why a generalized link is appropriate for the measurement scale.",
"A custom formula can be used when the recommended structure is not the intended model. The safe formula field accepts an outcome on the left and named random-effect terms separated by plus signs on the right. It rejects function calls, code execution, missing variables, and terms without replicated observations. This design provides flexibility for experienced users while keeping the model specification auditable. A manuscript should report the exact formula rather than only the coefficient produced by it.",
"The univariate G-study result has four layers. Fixed effects show the mean structure and selected covariates. Random effects show estimated variance components and their percentage of total variance. Other output contains model diagnostics, including singularity and convergence messages. The interpretation panel explains the largest nonperson source and points to D-study planning. A defensible interpretation reads all four layers together. For example, a high coefficient with a singular fit should not be presented as uncomplicated evidence of dependable scores.",
"The D-study workflow starts by opening the D-study controls after a successful G-study. The application initializes observed facet counts, lets the user select a facet, and provides a proposed number of conditions. After Apply facet levels, the updated table displays both observed and proposed counts. The analyst can repeat the process for several facets and compare the error denominators. A coefficient-path range produces a plot such as 4:16:4, which is useful for showing diminishing returns and for choosing a design that balances reliability with time, cost, or rater burden.",
"Bootstrap analysis is launched only after the G-study has succeeded. The user chooses the number of draws and processor cores. The interface displays progress and reports failed fits. A high failure rate is a diagnostic signal, not a reason to delete inconvenient draws without explanation. The downloaded interval table should be paired with the fitted formula, sample sizes, random seed, software versions, and any singular-fit or convergence warnings. In small designs, percentile intervals should be interpreted cautiously and compared with sensitivity analyses.",
"The multivariate path is an advanced feature for outcomes defined by a fixed facet. The user selects the fixed facet, enters semicolon-separated weights, and chooses facets with unstructured covariance. The resulting formula displays diagonal and unstructured terms, allowing the analyst to see which covariance assumptions are being fitted. The covariance table can be used to discuss whether dimensions share person-level or residual variation. Because weights and covariance structures affect the coefficient directly, the analyst should compare alternative specifications and explain the substantive meaning of the composite.",
"The AI Assistant can be used after configuration to ask questions such as which variance source is largest or how increasing raters changes the D-study. It receives variable names, sample sizes, formula text, and aggregate tables. It does not receive raw response rows. The privacy test in the repository asserts that identifiers and response vectors are absent from the generated context. The assistant is still fallible and should never be treated as an independent statistical reviewer. Its appropriate role is to help a learner formulate a question or understand displayed output.",
"Finally, the user should download the analysis artifacts. The transformed data document the data-shape decision; the structure table documents facet relationships; the formula documents the model; the G-study table documents variance decomposition; the bootstrap table documents uncertainty; and the D-study table documents the proposed design. Together these files form a compact audit trail that can accompany a manuscript or teaching exercise."
],
"Reporting Guidance and Use Cases": [
"For an applied manuscript, the minimum report should identify the measurement object, outcome scale, facets, crossed or nested design, missing-data rule, model formula, estimator, estimated variance components, relative and absolute error definitions, G and Phi, D-study conditions, confidence-interval method, and diagnostics. gTheoryShiny makes each of these fields available, but the user must transfer them into the report. A screenshot is useful evidence of the workflow, not a substitute for the numerical table or design description.",
"In classroom instruction, the app can be used in a progression. Students first compare raw and transformed tables, then predict the structure table, then fit a G-study and identify the largest error source. They can change one facet count at a time and explain why G and Phi differ. The bilingual control supports parallel discussion of technical vocabulary. An instructor can ask students to switch languages after fitting and verify that the same values remain selected, making state preservation itself an observable software property.",
"In assessment development, the app supports an iterative design conversation. A team can upload pilot data, identify whether rater or item variation dominates, and use the D-study panel to compare feasible allocations of conditions. The result is not an automatic optimization because costs, scheduling, and construct coverage are not fully encoded. Instead, the app supplies quantitative evidence that can be combined with operational constraints and validity arguments. This is consistent with recommendations to connect generalizability information to practical design improvement rather than treating reliability as an end point.",
"In consultation, the app can help an analyst separate data problems from model problems. If a facet has one level, the data validator identifies it. If a term has no replication, the estimability check reports it. If a model is singular, the result panel preserves the warning. If the coefficient changes after a missing-data choice, the user can compare runs. This sequence can make a consulting conversation more concrete than a final coefficient copied from an opaque program.",
"The application is also suitable for reproducible demonstrations. A repository release contains the application, test scripts, browser checks, synthetic examples, validation outputs, and screenshots. A reader can inspect the R functions that compute the G-study and D-study, compare them with independently coded formulas, and rerun the generated data. Such a package is particularly valuable for software-methods articles because it separates claims about interface behavior, statistical implementation, and empirical performance."
],
"Extended Limitations and Future Development": [
"The current implementation is intentionally narrower than a complete psychometric platform. It does not automatically select fixed versus random facets, determine a substantive universe of admissible observations, or decide whether a score should be reported. Its nesting screen is based on observed combinations and can be misleading under sparse sampling. Generalized-link models require more careful interpretation than the interface can provide. The experimental multivariate path may require more replication than a user has available, and an apparently successful optimizer does not prove that a covariance model is well identified.",
"The bootstrap implementation is parametric and conditional on the fitted model. It is not a universal solution to uncertainty in G-theory. Small numbers of persons, raters, or items can produce unstable intervals, boundary estimates, or failed refits. The interface reports those events, but the analyst must decide whether to simplify the design, collect additional data, compare bootstrap variants, or avoid a coefficient-based decision. The validation study therefore reports completion and implementation agreement rather than claiming universal interval coverage.",
"Future releases could add cost-constrained D-study optimization, cut-score-specific dependability, conditional standard errors of measurement, richer ordinal models, formal sensitivity reports, project files that bundle settings with data, and a visual model diagram. Multivariate extensions could include prior sensitivity and more extensive covariance diagnostics. A future evaluation should test unbalanced, partially crossed, missing-not-at-random, ordinal, and sparse designs and should compare the application with established G-theory programs using preregistered data-generating conditions.",
"The open-source workflow also creates maintenance responsibilities. Package versions can change optimizer behavior, browser widgets can change their event APIs, and translations can drift from statistical terminology. The regression tests and browser checks should therefore be run for each release. A release should record the R version, package versions, browser version, and validation results. Users should cite the immutable release rather than only the moving main branch."
],
}

# locate References heading and insert body before it
ref_index = next(i for i,p in enumerate(doc.paragraphs) if p.text.strip() == 'References')
anchor = doc.paragraphs[ref_index]
for title, paras in sections.items():
    h = anchor.insert_paragraph_before(title)
    h.style = doc.styles['Heading 1']
    for text in paras:
        p = anchor.insert_paragraph_before(text)
        p.paragraph_format.first_line_indent = Inches(.5)
        p.paragraph_format.line_spacing = 2

# append additional references after the existing references so the reference count is >= 30
extra_refs = [
'American Educational Research Association, American Psychological Association, & National Council on Measurement in Education. (2014). Standards for educational and psychological testing. American Educational Research Association.',
'Brennan, R. L. (1992). Generalizability theory. Educational Measurement: Issues and Practice, 11(4), 27–34. https://doi.org/10.1111/j.1745-3992.1992.tb00260.x',
'Brennan, R. L. (1998). Raw-score conditional standard errors of measurement in generalizability theory. Applied Psychological Measurement, 22(4), 307–331.',
'Brennan, R. L., Harris, D. J., & Hanson, B. A. (1987). The bootstrap and other procedures for examining the variability of estimated variance components in testing contexts. ACT Research Report.',
'Cardinet, J., Johnson, S., & Pini, G. (2010). Applying generalizability theory using EduG. Routledge.',
'Cronbach, L. J., Gleser, G. C., Nanda, H., & Rajaratnam, N. (1972). The dependability of behavioral measurements: Theory of generalizability for scores and profiles. Wiley.',
'Gao, X., & Brennan, R. L. (2001). Variability of estimated variance components and related statistics in a performance assessment. Applied Measurement in Education, 14(2), 191–203.',
'Gelman, A., & Hill, J. (2006). Data analysis using regression and multilevel/hierarchical models. Cambridge University Press.',
'Huebner, A., & Lucht, M. (2019). Generalizability theory in R. Practical Assessment, Research, and Evaluation, 24(5).',
'Jiang, Z., Walker, K., Shi, D., & Cao, J. (2018). Improving generalizability coefficient estimate accuracy: A way to incorporate auxiliary information. Methodological Innovations, 11(2). https://doi.org/10.1177/2059799118791397',
'Jiang, Z., Ouyang, J., Li, L., et al. (2022). Cost-effectiveness analysis in performance assessments: A case study of the objective structured clinical examination. Medical Education Online, 27(1), 2136559. https://doi.org/10.1080/10872981.2022.2136559',
'Kane, M. T. (2013). Validating the interpretations and uses of test scores. Journal of Educational Measurement, 50(1), 1–73.',
'Lane, S., Liu, M., Ankenmann, R. D., & Stone, C. A. (1996). Generalizability and validity of a mathematics performance assessment. Journal of Educational Measurement, 33(1), 71–92.',
'LoPilato, A. C., Carter, N. T., & Wang, M. (2015). Updating generalizability theory in management research: Bayesian estimation of variance components. Journal of Management, 41(2), 692–717.',
'Moore, C. (2016). gtheory: Apply generalizability theory with R [Computer software]. Comprehensive R Archive Network.',
'Nussbaum, A. (1984). Multivariate generalizability theory in educational measurement: An empirical study. Applied Psychological Measurement, 8, 219–230.',
'Raymond, M. R., & Jiang, Z. (2019). Indices of subscore utility for individuals and subgroups based on multivariate generalizability theory. Educational and Psychological Measurement, 79(6), 1061–1084. https://doi.org/10.1177/0013164419846936',
'Shavelson, R. J., & Webb, N. M. (1981). Generalizability theory: 1973–1980. British Journal of Mathematical and Statistical Psychology, 34(2), 133–166.',
'Sinharay, S., Johnson, M. S., Wang, W., et al. (2023). Targeted double scoring of performance tasks using a decision-theoretic approach. Applied Psychological Measurement, 47(2), 155–163.',
'Vispoel, W. P., Xu, G., & Schneider, W. S. (2022). Interrelationships between latent state-trait theory and generalizability theory in a structural equation modeling framework. Psychological Methods, 27, 773–803.',
'Vispoel, W. P., Lee, H., Xu, G., & Hong, H. (2022). Expanding bifactor models of psychological traits to account for multiple sources of measurement error. Psychological Assessment, 34, 1093–1111.',
'Wu, Y. F., & Tzou, H. (2015). A multivariate generalizability theory approach to standard setting. Applied Psychological Measurement, 39(7), 507–524.',
'Yin, P., & Sconing, J. (2008). Estimating standard errors of cut scores for item rating and bookmark procedures: A generalizability theory approach. Educational and Psychological Measurement, 68(1), 25–41.',
'Webb, N. M., Shavelson, R. J., & Haertel, E. H. (2006). Reliability coefficients and generalizability theory. In C. R. Rao & S. Sinharay (Eds.), Handbook of statistics (Vol. 26, pp. 81–124). Elsevier.'
]
for ref in extra_refs:
    p = doc.add_paragraph(); p.paragraph_format.left_indent=Inches(.5); p.paragraph_format.first_line_indent=Inches(-.5); p.paragraph_format.line_spacing=2; p.add_run(ref)

text='\n'.join(p.text for p in doc.paragraphs)
words=len(re.findall(r"\b[\w’'-]+\b", text))
print('total words including references:',words,'extra refs:',len(extra_refs))
doc.core_properties.author='Zhehan Jiang; Jihong Zhang; Tianpeng Zheng'
doc.save(source)

# recreate blinded copy
blind=Document(source)
for p in blind.paragraphs:
    if p.text.startswith(('Zhehan Jiang, Jihong Zhang, and Tianpeng Zheng','Institute of Medical Education','Corresponding authors:','Jihong Zhang is co-first','Author Note.')):
        p.text='[Author information removed for blinded review]'
blind.core_properties.author='Anonymous'
blind.save(root/'gTheoryShiny_EPM_manuscript_blinded.docx')
