app <- ShinyDriver$new("../../")
app$snapshotInit("RunDstudyUsingDat4")

app$uploadFile(`fileUpload-file` = "SyntheticDataSetNo.4.csv") # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$setInputs(rawDataTable_rows_current = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10), allowInputNoBinding_ = TRUE)
app$setInputs(rawDataTable_rows_all = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11), allowInputNoBinding_ = TRUE)
app$setInputs(rawDataTable_state = c(1684742015480, 0, 10, "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE)
app$setInputs(`fileUpload-isHeaderIncluded` = FALSE)
app$setInputs(rawDataTable_rows_current = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10), allowInputNoBinding_ = TRUE)
app$setInputs(rawDataTable_rows_all = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12), allowInputNoBinding_ = TRUE)
app$setInputs(rawDataTable_state = c(1684742018965, 0, 10, "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE)
app$setInputs(isLongFormat = FALSE)
app$setInputs(nRows = "2")
app$setInputs(TagPreFix = "t, ")
app$setInputs(TagPreFix = "t,r")
app$setInputs(TagNames = "Test,Ba")
app$setInputs(TagNames = "Test,Rater")
app$setInputs(transform = "click")
app$setInputs(transDataTable_rows_current = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10), allowInputNoBinding_ = TRUE)
app$setInputs(transDataTable_rows_all = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120), allowInputNoBinding_ = TRUE)
app$setInputs(transDataTable_state = c(1684742041095, 0, 10, "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE)
app$setInputs(selectedOutcome = "Score")
app$setInputs(variableSettingConfirm = "click")
app$setInputs(factorNestTable_rows_current = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10), allowInputNoBinding_ = TRUE)
app$setInputs(factorNestTable_rows_all = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12), allowInputNoBinding_ = TRUE)
app$setInputs(factorNestTable_state = c(1684742051994, 0, 10, "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE)
app$setInputs(nestedStrucTable_rows_current = 1, allowInputNoBinding_ = TRUE)
app$setInputs(nestedStrucTable_rows_all = 1, allowInputNoBinding_ = TRUE)
app$setInputs(nestedStrucTable_state = c(1684742051997, 0, 10, "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE)
app$setInputs(runGstudyButton = "click")
app$setInputs(runDstudyBox = TRUE)
app$setInputs(FacetDStudySelector = "Test")
app$setInputs(FacetValueSlider = 27)
app$setInputs(confirmFacetLevel = "click")
app$setInputs(FacetDStudySelector = c("Test", "Rater"))
app$setInputs(FacetDStudySelector = "Rater")
app$setInputs(FacetValueSlider = 37)
app$setInputs(confirmFacetLevel = "click")
app$setInputs(runDstudyButton = "click")
app$snapshot()
